### ISSUE TITLE
Cannot get maximize editor pane toggle to work with suggested key bindings

### ISSUE THREAD

**Issue by ariestav** [DavidBabel/clever-vscode#2]
Thank you for the extension.  I am particularly interested in getting the window pane maximization toggle to work with a keyboard shortcut.  

I inserted the following object into the array within my `keybindings.json` file:

```
    {
          "key"     : "shift+ctrl+enter"
        , "mac"     : "shift+cmd+enter" 
        , "command" : "clever.maximize.toggleWithSidebar"
        , "when"    : "editorTextFocus"
    }
```
I'm on macOS and yet, when my cursor is within an editor, and I hit `shit+cmd+enter` on my keyboard all that happens is that a new line is created.  I restarted VSCode to see if that was the issue, but alas same results.  What am I missing?  I noticed on the readme that `settings.json` might need to be adjusted, but I don't know where that is or if I really do need to change it.  Any suggestions are appreciated.

Thanks!

**Comment by DavidBabel** [comment]
Hey hi !

```js
{
  "key"     : "shift+cmd+enter"
  , "command" : "clever.maximize.toggleWithSidebar"
  , "when"    : "editorTextFocus"
    }
```
will do the trick
