### ISSUE TITLE
macro settings in keybinds.json not working

### ISSUE THREAD

**Issue by tyler-mitchell** [DavidBabel/clever-vscode#3]
Can't figure out why this error is occuring.
![image](https://user-images.githubusercontent.com/43253374/59073563-563b3d80-888d-11e9-820c-bdb360369495.png)

**Comment by DavidBabel** [comment]
You should create the macro first : 
https://marketplace.visualstudio.com/items?itemName=davidbabel.Clever&ssr=false#user-content-advanced-macros

The macros in the example are not provided in the extension out of the box, it's just an example you can use.
